/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import static ORG.oclc.z39.Z39initApi.password;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class prescriptionDR extends javax.swing.JFrame {
    private JFrame frame;

    /**
     * Creates new form prescriptionDR
     */
    public prescriptionDR() {
        initComponents();
        date();
        java.awt.Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public prescriptionDR(String Id) {
        initComponents();
        date();
        pID.setText(Id);
        java.awt.Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    public void date(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        date1.setText(dtf.format(now));
        date2.setText(dtf.format(now));
        date3.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        medicine1 = new javax.swing.JComboBox<>();
        reference1 = new javax.swing.JTextField();
        dailyDose1 = new javax.swing.JTextField();
        dose1 = new javax.swing.JTextField();
        medication1 = new javax.swing.JTextField();
        num1 = new javax.swing.JTextField();
        effects1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        medicine2 = new javax.swing.JComboBox<>();
        reference2 = new javax.swing.JTextField();
        dose2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        effects2 = new javax.swing.JTextField();
        medication2 = new javax.swing.JTextField();
        dailyDose2 = new javax.swing.JTextField();
        dailyDose3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        date3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        medicine3 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        reference3 = new javax.swing.JTextField();
        effects3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        num3 = new javax.swing.JTextField();
        medication3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dose3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        pID = new javax.swing.JTextField();
        pName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescription = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        prescribe = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(187, 225, 225));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Prescription");

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel2.setText("Name of Medicine 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setText("Reference No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));

        jLabel4.setText("Dose (mg)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel5.setText("Number of Medicines");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setText("Issued Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel7.setText("Daily Dose");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel8.setText("How to use medication");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel9.setText("Possible Side effects");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        medicine1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medicine", "Ace", "Ace Plus", "Denixil", "Elcet", "Fexo", "Monas", "Napa", "Napa Extra", "Napa One", "Pace", "Rosuva" }));
        medicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine1ActionPerformed(evt);
            }
        });
        jPanel1.add(medicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, 30));
        jPanel1.add(reference1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, 30));
        jPanel1.add(dailyDose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 280, -1));
        jPanel1.add(dose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 180, -1));

        medication1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(medication1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 280, -1));
        jPanel1.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 180, -1));
        jPanel1.add(effects1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 280, -1));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 180, -1));

        jLabel10.setText("Name of Medicine 2");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel11.setText("Reference No");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 80, -1));

        jLabel12.setText("Dose (mg)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        medicine2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medicine", "Ace", "Ace Plus", "Denixil", "Elcet", "Fexo", "Monas", "Napa", "Napa Extra", "Napa One", "Pace", "Rosuva" }));
        medicine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine2ActionPerformed(evt);
            }
        });
        jPanel1.add(medicine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 180, -1));
        jPanel1.add(reference2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 180, 20));
        jPanel1.add(dose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 180, -1));

        jLabel13.setText("Number of Medicines");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));
        jPanel1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 180, -1));

        jLabel14.setText("Issued Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 180, -1));

        jLabel15.setText("Daily Dose");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, -1, -1));

        jLabel16.setText("How to use medication");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        jLabel17.setText("Possible Side effects");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));
        jPanel1.add(effects2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 280, -1));
        jPanel1.add(medication2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 280, -1));
        jPanel1.add(dailyDose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 280, -1));
        jPanel1.add(dailyDose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 770, 280, -1));

        jLabel18.setText("Reference No");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, 80, -1));
        jPanel1.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 890, 180, -1));

        jLabel19.setText("Dose (mg)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 810, -1, -1));

        jLabel20.setText("Issued Date");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 890, -1, -1));

        medicine3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Medicine", "Ace", "Ace Plus", "Denixil", "Elcet", "Fexo", "Monas", "Napa", "Napa Extra", "Napa One", "Pace", "Rosuva" }));
        medicine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine3ActionPerformed(evt);
            }
        });
        jPanel1.add(medicine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 730, 180, -1));

        jLabel21.setText("Daily Dose");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 770, -1, -1));
        jPanel1.add(reference3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 770, 180, 20));
        jPanel1.add(effects3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 830, 280, -1));

        jLabel22.setText("How to use medication");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 800, -1, -1));

        jLabel23.setText("Name of Medicine 3");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, -1, -1));
        jPanel1.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 850, 180, -1));
        jPanel1.add(medication3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 800, 280, -1));

        jLabel24.setText("Number of Medicines");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 850, -1, -1));

        jLabel25.setText("Possible Side effects");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 830, -1, -1));
        jPanel1.add(dose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 810, 180, -1));

        jLabel26.setText("Age");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel27.setText("Patient ID");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel28.setText("Patient Name");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 60, -1));
        jPanel1.add(pID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));
        jPanel1.add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 230, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        jButton1.setText("Fetch Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 881, 1066));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        prescription.setColumns(40);
        prescription.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        prescription.setRows(5);
        jScrollPane1.setViewportView(prescription);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, -4, 720, 950));

        print.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        prescribe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prescribe.setText("Prescription");
        prescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescribeActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(prescribe)
                .addGap(51, 51, 51)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prescribe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 950, 730, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Hospital Management sytem",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
            prescription.print();
            
        }catch(PrinterException ex){
            Logger.getLogger(prescriptionDR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void medicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine1ActionPerformed
        // TODO add your handling code here:
        if (medicine1.getSelectedItem().equals("Ace"))
        {
            reference1.setText("ace0001");
            dose1.setText("500mg");
            num1.setText("30");
            dailyDose1.setText("3");
            medication1.setText("Take after meal, with water. No alcohol");
            effects1.setText("No Side effects");
        }
        if (medicine1.getSelectedItem().equals("Ace Plus"))
        {
            reference1.setText("ace0002");
            dose1.setText("655mg");
            num1.setText("12");
            dailyDose1.setText("2");
            medication1.setText("Take after meal, with water. No alcohol");
            effects1.setText("No Side effects");
        }
        if (medicine1.getSelectedItem().equals("Denixil"))
        {
            reference1.setText("den0001");
            dose1.setText("0.5mg");
            num1.setText("30");
            dailyDose1.setText("1");
            medication1.setText("Take after meal and slleping at night");
            effects1.setText("Dizziness, Weakness");
        }
        if (medicine1.getSelectedItem().equals("Elcet"))
        {
            reference1.setText("elc0001");
            dose1.setText("4mg");
            num1.setText("7");
            dailyDose1.setText("1");
            medication1.setText("Take after meal at night");
            effects1.setText("Oversleep, weekness");
        }
        if (medicine1.getSelectedItem().equals("Monas"))
        {
            reference1.setText("mon0001");
            dose1.setText("10mg");
            num1.setText("To be continued...");
            dailyDose1.setText("1");
            medication1.setText("Take one after dinner ");
            effects1.setText("Headache");
        }
        
    }//GEN-LAST:event_medicine1ActionPerformed

    private void prescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescribeActionPerformed
        // TODO add your handling code here:
        String Qty8 = (pID.getText());
        String Qty9 = (pName.getText());
        String Qty10 = (age.getText());
        String Qty0 = (medicine1.getSelectedItem().toString());
        String Qty1 = (reference1.getText());
        String Qty2 = (dose1.getText());
        String Qty3 = (num1.getText());
        String Qty4 = (date1.getText());
        String Qty5 = (dailyDose1.getText());
        String Qty6 = (medication1.getText());
        String Qty7 = (effects1.getText());
        
        
        String Qty11 = (medicine2.getSelectedItem().toString());
        String Qty12 =(reference2.getText());
        String Qty13= (dose2.getText());
        String Qty14= (num2.getText());
        String Qty15= (date2.getText());
        String Qty16= (dailyDose2.getText());
        String Qty17= (medication2.getText());
        String Qty18= (effects2.getText());
        
        
        
        String Qty19 = (medicine3.getSelectedItem().toString());
        String Qty20 =(reference3.getText());
        String Qty21= (dose3.getText());
        String Qty22= (num3.getText());
        String Qty23= (date3.getText());
        String Qty24= (dailyDose3.getText());
        String Qty25= (medication3.getText());
        String Qty26= (effects3.getText());
        
        
        prescription.setText("");
        prescription.append("\t\n\t\t\t    Hospital Management Systems\n"
        +"\nPatient ID  :\t" + Qty8
        +"\nPatient Name:\t" + Qty9
        +"\nPatient Age :\t" + Qty10
        +"\n\nMedicine Name:\t" + Qty0
        +"\nReference No:\t" + Qty1
        +"\nDose(mg)    :\t" + Qty2
        +"\nTotal Amount:\t" + Qty3
        +"\nIssued Date :\t" + Qty4
        +"\nDaily Amount:\t" + Qty5
        +"\nMedications :\t" + Qty6
        +"\nEffects     :\t" + Qty7
        +"\n"
        +"\nMedicine Name:\t" + Qty11
        +"\nReference No:\t" + Qty12
        +"\nDose(mg)    :\t" + Qty13
        +"\nTotal Amount:\t" + Qty14
        +"\nIssued Date :\t" + Qty15
        +"\nDaily Amount:\t" + Qty16
        +"\nMedications :\t" + Qty17
        +"\nEffects     :\t" + Qty18
        +"\n"       
        +"\nMedicine Name:\t" + Qty19
        +"\nReference No:\t" + Qty20
        +"\nDose(mg)    :\t" + Qty21
        +"\nTotal Amount:\t" + Qty22
        +"\nIssued Date :\t" + Qty23
        +"\nDaily Amount:\t" + Qty24
        +"\nMedications :\t" + Qty25
        +"\nEffects     :\t" + Qty26
        );
        
        
    }//GEN-LAST:event_prescribeActionPerformed

    private void medicine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine2ActionPerformed
        // TODO add your handling code here:
        if (medicine2.getSelectedItem().equals("Ace"))
        {
            reference2.setText("ace0001");
            dose2.setText("500mg");
            num2.setText("30");
            dailyDose2.setText("3");
            medication2.setText("Take after meal, with water. No alcohol");
            effects2.setText("No Side effects");
        }
        if (medicine2.getSelectedItem().equals("Ace Plus"))
        {
            reference2.setText("ace0002");
            dose2.setText("655mg");
            num2.setText("12");
            dailyDose2.setText("2");
            medication2.setText("Take after meal, with water. No alcohol");
            effects2.setText("No Side effects");
        }
        if (medicine2.getSelectedItem().equals("Denixil"))
        {
            reference2.setText("den0001");
            dose2.setText("0.5mg");
            num2.setText("30");
            dailyDose2.setText("1");
            medication2.setText("Take after meal and slleping at night");
            effects2.setText("Dizziness, Weakness");
        }
        if (medicine2.getSelectedItem().equals("Elcet"))
        {
            reference2.setText("elc0001");
            dose2.setText("4mg");
            num2.setText("7");
            dailyDose2.setText("1");
            medication2.setText("Take after meal at night");
            effects2.setText("Oversleep, weekness");
        }
        if (medicine2.getSelectedItem().equals("Monas"))
        {
            reference2.setText("mon0001");
            dose2.setText("10mg");
            num2.setText("To be continued...");
            dailyDose2.setText("1");
            medication2.setText("Take one after dinner ");
            effects2.setText("Headache");
        }
    }//GEN-LAST:event_medicine2ActionPerformed

    private void medicine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine3ActionPerformed
        // TODO add your handling code here:
        if (medicine3.getSelectedItem().equals("Ace"))
        {
            reference3.setText("ace0001");
            dose3.setText("500mg");
            num3.setText("30");
            dailyDose3.setText("3");
            medication3.setText("Take after meal, with water. No alcohol");
            effects3.setText("No Side effects");
        }
        if (medicine3.getSelectedItem().equals("Ace Plus"))
        {
            reference3.setText("ace0002");
            dose3.setText("655mg");
            num3.setText("12");
            dailyDose3.setText("2");
            medication3.setText("Take after meal, with water. No alcohol");
            effects3.setText("No Side effects");
        }
        if (medicine3.getSelectedItem().equals("Denixil"))
        {
            reference3.setText("den0001");
            dose3.setText("0.5mg");
            num3.setText("30");
            dailyDose3.setText("1");
            medication3.setText("Take after meal and slleping at night");
            effects3.setText("Dizziness, Weakness");
        }
        if (medicine3.getSelectedItem().equals("Elcet"))
        {
            reference3.setText("elc0001");
            dose3.setText("4mg");
            num3.setText("7");
            dailyDose3.setText("1");
            medication3.setText("Take after meal at night");
            effects3.setText("Oversleep, weekness");
        }
        if (medicine3.getSelectedItem().equals("Monas"))
        {
            reference3.setText("mon0001");
            dose3.setText("10mg");
            num3.setText("To be continued...");
            dailyDose3.setText("1");
            medication3.setText("Take one after dinner ");
            effects3.setText("Headache");
        }
        
    }//GEN-LAST:event_medicine3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Id=pID.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from newpatient where patientID='"+Id+"'");
            if(rs.next()){
                pName.setText(rs.getString(2)+rs.getString(3));
                age.setText(rs.getString(4));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection error" );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","");
            Statement statement = con.createStatement();
            statement.executeUpdate("INSERT INTO prescription VALUES('"+pID.getText()+"','"+pName.getText()+"','"+age.getText()+"','"+medicine1.getSelectedItem()+"','"+reference1.getText()+"','"+dose1.getText()+"','"+num1.getText()+"','"+date1.getText()+"','"+dailyDose1.getText()+"','"+medication1.getText()+"','"+effects1.getText()+"','"+medicine2.getSelectedItem()+"','"+reference2.getText()+"','"+dose2.getText()+"','"+num2.getText()+"','"+date2.getText()+"','"+dailyDose2.getText()+"','"+medication2.getText()+"','"+effects2.getText()+"','"+medicine3.getSelectedItem()+"','"+reference3.getText()+"','"+dose3.getText()+"','"+num3.getText()+"','"+date3.getText()+"','"+dailyDose3.getText()+"','"+medication3.getText()+"','"+effects3.getText()+"')");
            JOptionPane.showMessageDialog(null,"Prescription Updated.");
            statement.close();
            con.close();
            Refresh();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new patientProfile().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prescriptionDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prescriptionDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prescriptionDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prescriptionDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prescriptionDR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField dailyDose1;
    private javax.swing.JTextField dailyDose2;
    private javax.swing.JTextField dailyDose3;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date2;
    private javax.swing.JTextField date3;
    private javax.swing.JTextField dose1;
    private javax.swing.JTextField dose2;
    private javax.swing.JTextField dose3;
    private javax.swing.JTextField effects1;
    private javax.swing.JTextField effects2;
    private javax.swing.JTextField effects3;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medication1;
    private javax.swing.JTextField medication2;
    private javax.swing.JTextField medication3;
    private javax.swing.JComboBox<String> medicine1;
    private javax.swing.JComboBox<String> medicine2;
    private javax.swing.JComboBox<String> medicine3;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField pID;
    private javax.swing.JTextField pName;
    private javax.swing.JButton prescribe;
    private javax.swing.JTextArea prescription;
    private javax.swing.JButton print;
    private javax.swing.JTextField reference1;
    private javax.swing.JTextField reference2;
    private javax.swing.JTextField reference3;
    // End of variables declaration//GEN-END:variables

    private void Refresh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
